#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd ~/.dotfiles

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
